### ISSUE TITLE
sub folder for auton

### ISSUE THREAD

**Issue by xavierlyu** [Team1923/Stronghold_2016#4]
Is it a good idea to have a sub-folder(or package) inside the commands folder for autons routines?
We can call it _auton_

**Comment by cuuush** [comment]
Since auton routines are just command groups, and we generally keep command groups in the command package, I think keeping them where they are now is fine. Moving them to their own package would make it harder for the autons to call commands since each command group needs to import the commands package. We just prefix the class with Auton, which has worked so far.

**Comment by xavierlyu** [comment]
OK, that explains a lot

**Comment by Makarand12676** [comment]
Also sometimes same command can be used in teleop and auton. So do not
create duplicate command for each routine. Basic principle of good
programming - no duplicate code :). It helps to maintain and fix is
required at one place only.
